### ISSUE TITLE
[feature] 에러 디버깅을 위해, 디스코드를 활용한다.

### ISSUE THREAD

**Issue by kpeel5839** [mafia-together/backend#134]
## Describe

Feign Client를 추가하고, 이를 통해 Discord Webhook을 활용해 error를 알린다.

## Tasks

- [x] FeignClient 의존성 추가
- [x] Discord 의존성 추가
- [x] Discord 웹훅 추가
- [x] 로직 작성
