### ISSUE TITLE
[refactoring] 테스트 리팩터링

### ISSUE THREAD

**Issue by waterricecake** [mafia-together/backend#154]
## Describe
테스트 리펙터링을 진행해봅시다.
<img width="473" alt="스크린샷 2024-11-13 오전 12 50 47" src="https://github.com/user-attachments/assets/b4c0df84-fd5d-4cb2-a1c4-038eb0250fca">

## Tasks
- [ ] chat, common, game, job의 테스트 추가
- [ ] 서비스 단인 Listener들을 모킹해서 테스트한 것 처럼 다른 서비스들도 전부 mocking으로 바꾸기
- [ ] 엣지케이스들을 추가( 실패테스트 )
