### ISSUE TITLE
api 수정 사항 반영

### ISSUE THREAD

**Issue by waterricecake** [mafia-together/backend#29]
## Describe
2024/5/8 api 수정 사항 반영하기
## Tasks
- [ ] Player Api url 수정
- [ ] role -> job 용어 수정
- [ ] name -> target 용어 수정
- [ ] 방 검증 코드 API 구현
- [ ] 채팅 내역 'owner' -> 'isOwner'
