### ISSUE TITLE
예외 사항 구현

### ISSUE THREAD

**Issue by waterricecake** [mafia-together/backend#36]
## Describe
기타 상황들에서 예외 사항들을 추가
## Tasks
- [x] 방 만들기에서 roominfo 조건 점검
- [x] 방 참가하기 조건 점검
   - [x] 방이 다 찼는지 점검
   - [x] 이름 중복 점검
- [x] 게임 시작시 시작 조건 점검
- [x] 채팅 전송시 빈 문자열 점검
- [x] 플레이어별 직업 기술 수행 점검
   - [x] 죽은 사람 타겟 점검
   - [x] target이 player에 있는지 점검
- [x] 마피아 타겟 조회 시 마피아 인지 점검
