### ISSUE TITLE
방 상태 추가하기

### ISSUE THREAD

**Issue by waterricecake** [mafia-together/backend#42]
## Describe
대기 : “WAIT”
낮이되었습니다: “DAY-INTRO”
본인 직업 OR 어젯밤죽은사람 공지: “NOTICE”
낮 : “DAY”
투표 : “VOTE”
투표결과: “VOTE_RESULT”
밤이 찾아왔습니다: “NIGHT-INTRO”
밤 : “NIGHT”
종료 : ”END”

## Tasks
- [ ] DAY-INTRO 추가
- [ ] NOTICE 추가
- [ ] VOTE_RESULT 추가
- [ ] NIGTH-INTRO 추가
