### ISSUE TITLE
QA Bug Fix

### ISSUE THREAD

**Issue by waterricecake** [mafia-together/backend#64]
## Describe
요약
## Tasks
- [x]  밤 결과 예외처리 수정(Day Intro가 아니라 Notice임) 
- [x]  마피아 안죽이기 수정 (김동연)
- [x] 투표하기에서 죽은사람를 투표수에서 제거
- [x] 채팅방 초기화
