### ISSUE TITLE
패키지 별 의존성 분리 및 레디스 도입

### ISSUE THREAD

**Issue by waterricecake** [mafia-together/backend#84]
## Describe
<img width="200" alt="스크린샷 2024-07-20 오후 8 21 52" src="https://github.com/user-attachments/assets/510e1fcd-7977-499b-9431-368bfb7241f6">

분리한 패키지간 의존성을 분리하며 Redis를 도입한다
## Tasks
- [ ] Room - Vote 의존성 분리
- [ ] Room - Job 의존성 분리
- [ ] Room - Chatting 의존성 분리
- [ ] Room - Game 의존성 분리
- [ ] Room - Invite 의존성 분리
